CREATE OR REPLACE PROCEDURE SP_PH_LOG(pID_USER in varchar2, pIP in varchar2, pEVENTO in varchar2,
pDATOS in varchar2, pSQL in varchar2, pJUSTIFICACION in varchar2) IS
BEGIN

      INSERT INTO PH_LOG(ID_LOG, ID_USER, IP, EVENTO, DATOS, SQL, JUSTIFICACION)
      VALUES(SEQ_PH_LOG.NEXTVAL, pID_USER, pIP, pEVENTO, pDATOS, pSQL, pJUSTIFICACION);

END SP_PH_LOG;
/
